const fontFamilies = [
    'Arial, sans-serif',
    'Verdana, sans-serif',
    'Helvetica, sans-serif',
    'Times New Roman, serif',
    'Georgia, serif',
    'Courier New, monospace',
    'Lucida Console, monospace',
    'Tahoma, sans-serif',
    'Trebuchet MS, sans-serif',
    'Palatino, serif',
    'Garamond, serif',
    'Comic Sans MS, cursive',
    'Impact, sans-serif',
    'Franklin Gothic Medium, sans-serif',
    'Gill Sans, sans-serif',
    'Century Gothic, sans-serif',
    'Lucida Sans, sans-serif',
    'Brush Script MT, cursive',
    'Copperplate, serif',
    'Futura, sans-serif',
    'Optima, sans-serif',
    'Rockwell, serif',
    'Baskerville, serif',
    'Segoe UI, sans-serif',
    'Candara, sans-serif',
    'Geneva, sans-serif',
    'Roboto, sans-serif',
    'Montserrat, sans-serif',
    'Lato, sans-serif',
    'Merriweather, serif',
    'Open Sans, sans-serif',
    'Raleway, sans-serif',
    'Ubuntu, sans-serif',
    'PT Serif, serif'
];

export default fontFamilies